# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: /home/kiott01a/kiotta/fpga/1/mpu6050_hw/mpu6050_hw.srcs/sources_1/bd/i2c_mpu6050/ip/i2c_mpu6050_processing_system7_0_0/i2c_mpu6050_processing_system7_0_0.xci
# IP: The module: 'i2c_mpu6050_processing_system7_0_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: /home/kiott01a/kiotta/fpga/1/mpu6050_hw/mpu6050_hw.srcs/sources_1/bd/i2c_mpu6050/ip/i2c_mpu6050_processing_system7_0_0/i2c_mpu6050_processing_system7_0_0.xdc
# XDC: The top module name and the constraint reference have the same name: 'i2c_mpu6050_processing_system7_0_0'. Do not add the DONT_TOUCH constraint.
set_property DONT_TOUCH TRUE [get_cells inst -quiet] -quiet

# IP: /home/kiott01a/kiotta/fpga/1/mpu6050_hw/mpu6050_hw.srcs/sources_1/bd/i2c_mpu6050/ip/i2c_mpu6050_processing_system7_0_0/i2c_mpu6050_processing_system7_0_0.xci
# IP: The module: 'i2c_mpu6050_processing_system7_0_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: /home/kiott01a/kiotta/fpga/1/mpu6050_hw/mpu6050_hw.srcs/sources_1/bd/i2c_mpu6050/ip/i2c_mpu6050_processing_system7_0_0/i2c_mpu6050_processing_system7_0_0.xdc
# XDC: The top module name and the constraint reference have the same name: 'i2c_mpu6050_processing_system7_0_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells inst -quiet] -quiet
