# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# XDC: new/zybo_z7.xdc

# Block Designs: bd/i2c_mpu6050/i2c_mpu6050.bd
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==i2c_mpu6050 || ORIG_REF_NAME==i2c_mpu6050} -quiet] -quiet

# IP: bd/i2c_mpu6050/ip/i2c_mpu6050_processing_system7_0_0/i2c_mpu6050_processing_system7_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==i2c_mpu6050_processing_system7_0_0 || ORIG_REF_NAME==i2c_mpu6050_processing_system7_0_0} -quiet] -quiet

# XDC: bd/i2c_mpu6050/i2c_mpu6050_ooc.xdc
