set_property SRC_FILE_INFO {cfile:/home/kiott01a/kiotta/fpga/1/mpu6050_hw/mpu6050_hw.srcs/constrs_1/new/zybo_z7.xdc rfile:../../../mpu6050_hw.srcs/constrs_1/new/zybo_z7.xdc id:1} [current_design]
set_property src_info {type:XDC file:1 line:3 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN V12 [get_ports IIC_0_0_scl_io]
set_property src_info {type:XDC file:1 line:4 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN W16 [get_ports IIC_0_0_sda_io]
